// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdaoaoqhgnyiiwipfioe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkYW9hb3FoZ255aWl3aXBmaW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTIxNDEsImV4cCI6MjA1ODY2ODE0MX0.rYLeWGBV1DD5zjOu41d0MmK0kJOpkIN5dMG_L1fAqG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);